### ISSUE TITLE
dsc_registry generates notify event for every time puppet agent launches

### ISSUE THREAD

**Issue by marcinbojko** [puppetlabs/puppetlabs-dsc#237]
1. Description
   Setting any value in registry returns notify every time agent launches:

> Notice: /Stage[main]/xxmodule/Dsc_registry[tightvncpassword]/ensure: created
> Notice: /Stage[main]/xxmodule/Dsc_registry[tightvncpasswordcontrol]/ensure: created``
1. Expected behaviour
   Notice generated only once or with dsc_force=true

Example:

```

tightvncpassword:
  dsc_key: HKEY_LOCAL_MACHINE\SOFTWARE\TightVNC\Server
  dsc_valuename: Password
  dsc_hex: true
  dsc_valuedata: 00 00 00 00 00 00 00
  dsc_valuetype: binary
```
